### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by PalePyth** [Abastro/Stellarium#5]
Good idea, man. But when I use your mod (1.7.10) my FPS is over 10! But regular I have 60 FPS. Can you do something with it?

**Comment by Abastro** [comment]
Please, this mod is not published yet.
Previous versions of Stellarium had updated to Stellar Sky, so use that.

**Comment by PalePyth** [comment]
I used the Stellar Sky for my test. That's sad.

**Comment by Abastro** [comment]
Then post this issue to Stellar Sky.
